language: go
go:
- '1.12'
env:
- GO111MODULE=on
script:
- make test
notifications:
  slack:
    secure: h7dfGEWWfChnonvRuOFV6k3PLLNAZsdxYUbR+qOzXOE6QXr4Wur4CWuUQ3SwVDI50zw1CNSl6wZN31jEE6R7EA+/a/EXxg0+rkOnuthRRaSdPWi36Vz7hmkHnW9sJorN2HZkO9h3UQj3ypDzvewL0rzP/Jgy6Jsyu5YdixclACZ9LkGpIPoWjCQc/EVsqPe5Wm4GMeA3Tbk3EE+vKdZ3IYXE1o1Pkk7E23VlqTFX4RNrxW8EwkxwYJfV5RhJXhJlyf/SilciyCgAQzcc57A6L1YMDPsZZdJceQurhLG1ROR0wZCAqxkj9cR/Sv9GHILhBIEBn6FDNt7m//4lPhtHy+2ZuPZ+Kn+UlNthuRXgszc2tsa3QEtCN585qUm7uJ3UgHGUUdfupHHYhGHGTarUGYXSg/SBS3sxeTySyaRWCXEyVmSzf8odTdfM5E5AnuMxyGRwv/IHlt+QESmrTACSEa4fZS9aTzRx63tJBP8Q4RjiNNPqh+fcvGLPXIKxRtCxD7Wa2ibd0Qd8QbzQhygmQlkspHXFhSY0Ev78XL8kOOJ8hR9ZibEACtxJK4OA2QgYtIPWMxaDp//cby9mkGFV/N7TyGDvb8Ef5GEJXB7qOXFn3SBpYcALNc0jwA1Y4faUjam7JaVhpuzDNvwW5H1ZRiQw7W1k80h0vnpoHiZ/s54=
